grades = [90, 75, 100, 55, 90, 60]
print('1. time 90 appers:', grades.count(90))
print('2. index of first 100:', grades.index(100))
grades.append(88)
grades.insert(2, 50 )
grades.remove(55)
remove_grades = grades.pop(3)
print(f'removed grade at index 3 was: {remove_grades}')
print('maximum garde:', max(grades))
print('minimum garde:', min(grades))
print('total sum of garde:', sum(grades))
print('number of gardes :', len(grades))
backup_grades = grades.copy()
grades.clear()
print('original list (after clear):', grades)
print('backup list', backup_grades)